#!/bin/sh

DATE=$(date +%Y-%m-%d_%H-%M-%S)

if [ ! -d "${HOME}/.config/backups/${DATE}" ]; then
  mkdir "${HOME}/.config/backups/${DATE}"
fi
if [ ! -d "${HOME}/.config/temp" ]; then
  mkdir "${HOME}/.config/temp"
fi

# /Users/annieehler/.config/nvim/init.lua
if [ -d "${HOME}/.config/nvim" ]; then
  unlink "${HOME}/.config/nvim"
fi
# /Users/annieehler/.config/starship.toml
if [ -f "${HOME}/.config/starship.toml" ]; then
  unlink "${HOME}/.config/starship.toml"
fi
# /Users/annieehler/.config/fish/config.fish
if [ -d "${HOME}/.config/fish" ]; then
  unlink "${HOME}/.config/fish"
fi

if [ -d "${HOME}/.config/nixpkgs" ]; then
  cp -Lr "${HOME}/.config/nixpkgs" "${HOME}/.config/backups/${DATE}/nixpkgs"
  rm -rd "${HOME}/.config/nixpkgs"
fi
cp -r "${HOME}/.config/dotfiles/nixpkgs" "${HOME}/.config/nixpkgs"

POSITIONAL_ARGS=()
UPDATE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    -u|-U|--update)
      UPDATE=true # set to update
      shift # past argument
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

darwin-rebuild check --flake "$HOME/.config/nixpkgs"

if [ ${#POSITIONAL_ARGS[@]} -gt 0 ]; then
  darwin-rebuild "${POSITIONAL_ARGS[@]}"
elif [ "$UPDATE" = true ]; then
  darwin-rebuild build --recreate-lock-file --flake "$HOME/.config/nixpkgs" "${POSITIONAL_ARGS[@]}"
  darwin-rebuild switch --refresh --flake "$HOME/.config/nixpkgs" "${POSITIONAL_ARGS[@]}"
else
  darwin-rebuild build --flake "$HOME/.config/nixpkgs" "${POSITIONAL_ARGS[@]}"
  darwin-rebuild switch --flake "$HOME/.config/nixpkgs" "${POSITIONAL_ARGS[@]}"
fi

if [ -d "${HOME}/.config/nixpkgs" ]; then
  sudo rm -rd "${HOME}/.config/nvim"
fi

if [ -f "${HOME}/.config/starship.toml" ]; then
  sudo rm -rd "${HOME}/.config/starship.toml"
fi

if [ -d "${HOME}/.config/fish" ]; then
  sudo rm -rd "${HOME}/.config/fish"
fi

ln -s "${HOME}/.config/dotfiles/nvim" "${HOME}/.config/nvim"
ln -s "${HOME}/.config/dotfiles/starship.toml" "${HOME}/.config/starship.toml"
ln -s "${HOME}/.config/dotfiles/fish" "${HOME}/.config/fish"
